# Generated by Django 4.0.5 on 2022-06-04 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=100)),
                ('job_department', models.CharField(choices=[('SDE1', 'SDE1'), ('SDE2', 'SDE2'), ('Data Scientist', 'Data Scientist'), ('Data Analyst', 'Data Analyst'), ('Financial analyst', 'Financial analyst'), ('Sales representative', 'Sales representative'), ('Human resources', 'Human resources'), ('Marketing coordinator', 'Marketing coordinator'), ('Operations', 'Operations'), ('Environmental Engineer', 'Environmental Engineer')], default='Operations', max_length=200)),
                ('mafiosos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.mafioso')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.applicant')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.job')),
                ('maafiosos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.mafioso')),
            ],
        ),
    ]
