# Generated by Django 4.0.5 on 2022-06-04 21:42

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='static/user/profile_pic/'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Resilience', 'Resilience'), ('Good communication', 'Good communication'), ('Leadership', 'Leadership'), ('Management', 'Management'), ('Adaptability', 'Adaptability'), ('Team Player', 'Team Player'), ('Problem Solving Skills', 'Problem Solving Skills'), ('Critical Thinking Skills', 'Critical Thinking Skills'), ('Flexibility', 'Flexibility'), ('Organization Skills', 'Organization Skills'), ('Management', 'Management'), ('Adaptability', 'Adaptability'), ('Creativity', 'Creativity'), ('Computer Software and Application Knowledge', 'Computer Software and Application Knowledge'), ('Data Analysis', 'Data Analysis'), ('Project Management', 'Project Management'), ('Marketing', 'Marketing'), ('Coding', 'Coding'), ('Debugging', 'Debugging'), ('C++', 'C++'), ('SQL', 'SQL'), ('Python', 'Python'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('Servers', 'Servers'), ('Network Security', 'Network Security'), ('SAS', 'SAS'), ('Machine Learning', 'Machine Learning'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Algorithms', 'Algorithms'), ('Big Data', 'Big Data')], max_length=416, null=True),
        ),
    ]
