# Generated by Django 4.0.5 on 2022-06-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_applicant_profile_pic_alter_applicant_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='quiz_score',
        ),
    ]
